config/routes.rb
TheCloudOfImage::Application.routes.draw do

  resources :camera_places
  get "camera_places/add_place_moniter/:camera_place_id" => "camera_places#add_place_moniter", :as => 'add_place_moniter'

  resources :cameras
  get "cameras/show_by_place/:camera_place_id" => "cameras#show_by_place", :as => "show_by_place"

  post "group_api/index"
  post "api_user/index"
  post "api_moniter_place/index"
  post "api_system/index"

  post "api/index"
  get "api/index"
  post "api/upload"
  post "moniter/upload"

  resources :convert_rules

  get "images/display/:filename.:format\!:convert_rule" => "images#convert", :as=>'convert_image'
  get "images/display/:filename" => "images#display", :as=>'display_image'

  resources :images do
  end

  get "site/index"
  get "site/pjax", :as=>'pjax'

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}

  root :to => 'site#index'

end

app/models/camera_place.rb
class CameraPlace < ActiveRecord::Base
  attr_accessible :place, :status
  has_many :cameras
  validates_uniqueness_of :place, :scope => :user_id

  default_scope where(:status => 1)
end

app/controllers/camera_places_controller.rb
class CameraPlacesController < ApplicationController
  before_filter :authenticate_user!, :set_page_name

  def add_place_moniter
    user = current_user
    @place = user.CameraPlaces.where(:id => params[:camera_place_id]).first
    if not @place
      return render_404
    end
    #@camera_place = CameraPlace.find(params[:camera_place_id])
  end

  # GET /camera_places
  # GET /camera_places.json
  def index
    user = current_user
    @camera_places = user.CameraPlaces

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @camera_places }
    end
  end

  # GET /camera_places/1
  # GET /camera_places/1.json
  def show
    @camera_place = CameraPlace.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camera_place }
    end
  end

  # GET /camera_places/new
  # GET /camera_places/new.json
  def new
    @camera_place = CameraPlace.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @camera_place }
    end
  end

  # GET /camera_places/1/edit
  def edit
    @camera_place = CameraPlace.find(params[:id])
  end

  # POST /camera_places
  # POST /camera_places.json
  def create
    user = current_user
    @camera_place = CameraPlace.new(params[:camera_place])
    @camera_place.user_id = user.id

    respond_to do |format|
      if @camera_place.save
        format.html { redirect_to camera_places_path, notice: 'Camera place was successfully created.' }
        format.json { render json: @camera_place, status: :created, location: @camera_place }
      else
        format.html { render action: "new" }
        format.json { render json: @camera_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /camera_places/1
  # PUT /camera_places/1.json
  def update
    @camera_place = CameraPlace.find(params[:id])

    respond_to do |format|
      if @camera_place.update_attributes(params[:camera_place])
        format.html { redirect_to @camera_place, notice: 'Camera place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @camera_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camera_places/1
  # DELETE /camera_places/1.json
  def destroy
    @camera_place = CameraPlace.find(params[:id])
    @camera_place.destroy

    respond_to do |format|
      format.html { redirect_to camera_places_url }
      format.json { head :no_content }
    end
  end

  private
    def set_page_name
      @page_name = "camera_places"
    end
end

app/helpers/camera_places_helper.rb
module CameraPlacesHelper
end

app/views/camera_places/_form.html.erb
<div style='clear:both'></div>
<%= form_for(@camera_place) do |f| %>
  <% if @camera_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camera_place.errors.count, "error") %> prohibited this camera_place from being saved:</h2>

      <ul>
      <% @camera_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :场所名称 %>
    <%= f.text_field :place %>
    <%= f.number_field :status, :value=>1, :style=>'display:none' %>
  </div>
  <div class="actions">
    <%= f.submit :创建, :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/camera_places/add_place_moniter.html.erb
<div class="pull-left">
  <h3>
    <%= @place.place %> 监控
    <button id="snap" class="btn btn-primary">开始监控</button>
  </h3>
</div>
<div class="pull-right">
  <h1>
    <%= link_to '返回', camera_places_path, :class=>'btn' %></h1>
</div>
<div style='clear:both'></div>
<video id="video" style="width:320px;height:240px;" autoplay></video>
<br/>
<img id="img" src="" />
<canvas id="canvas" style='display:none' width="320" height="240"></canvas>
    <script>
    function hasGetUserMedia() {
        // Note: Opera is unprefixed.
        return !!(navigator.getUserMedia || navigator.webkitGetUserMedia ||
                navigator.mozGetUserMedia || navigator.msGetUserMedia);
    }
    function getMedia()
    {
        return navigator.getUserMedia || navigator.webkitGetUserMedia ||
                navigator.mozGetUserMedia || navigator.msGetUserMedia;
    }


    </script>
    <script>
        // Put event listeners into place
        window.addEventListener("DOMContentLoaded", function() {
            if (hasGetUserMedia()) {
                // Good to go!
            } else {
                alert('您的浏览器还不支持该功能, 建议您升级至最新版 chrome 或者 firefox 浏览器');
                return;
            }
            var post_params = {'camera_place_id': <%= @place.id%>};
            // Grab elements, create settings, etc.
            var canvas = document.getElementById("canvas"),
                context = canvas.getContext("2d"),
                video = document.getElementById("video"),
                img = document.getElementById("img"),
                videoObj = { "video": true },
                localMediaStream = null,
                errBack = function(error) {
                    alert("抱歉, 发生错误 " + error); 
                };

            // Put video listeners into place
            if(navigator.getUserMedia) { // Standard
                navigator.getUserMedia(videoObj, function(stream) {
                    video.src = stream;
                    video.controls = true;

                    localMediaStream = stream;
                }, errBack);
            } else if(navigator.webkitGetUserMedia) { // WebKit-prefixed
                navigator.webkitGetUserMedia(videoObj, function(stream){
                    var vendorURL = window.URL || window.webkitURL;
                    video.src = window.webkitURL.createObjectURL(stream);
                    video.controls = true;
                    localMediaStream = stream;
                    video.play();
                }, errBack);

            } else if (navigator.mozGetUserMedia ) {
                navigator.mozGetUserMedia(videoObj, function(stream1){
                    video.src = window.URL.createObjectURL(stream1);
                    localMediaStream = stream1;
                    video.play();
                }, errBack);
            }


            var upload_camera_pic = function() {
              context.drawImage(video, 0 , 0, 320, 240);
              img.src = canvas.toDataURL('image/jpeg');

              var post_params_this = post_params;
              var imgData =canvas.toDataURL("image/jpeg");
              var data = imgData.substr(23);  
              post_params_this['image_data'] = data;
              $.post(
                '<%= cameras_path%>',
                post_params_this, 
                function(data, textStatus, jqXHR){
                  //success
                }, 
                "json");
            }

            var upload = function(){
              if (! window.start_monitor) {
                return;
              }
              upload_camera_pic();
              window.set_timeout = setTimeout(upload, 3000);
            }

            window.start_monitor = false;
            // Trigger photo take
            $("#snap").click(function(){
              if (!window.start_monitor) {
                $(this).text("停止监控");
                window.start_monitor = true;
                upload();
              }else{
                $(this).text("开始监控");
                window.start_monitor = false;
              }
            });

        }, false);
    </script>

app/views/camera_places/edit.html.erb
<h1>Editing camera_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @camera_place %> |
<%= link_to 'Back', camera_places_path %>

app/views/camera_places/index.html.erb
<div class="pull-left">
  <h3>我的监控</h3>
</div>
<div class="pull-right">
  <h1><%= link_to '新建场所', new_camera_place_path, :class=>'btn btn-primary' %></h1>
</div>

<table class="table">
  <thead>
  <tr>
    <th>地点</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

<% @camera_places.each do |camera_place| %>
  <tr>
    <td><%= camera_place.place %></td>
    <td>
      <%= link_to '监控', add_place_moniter_path(camera_place.id), :class => 'btn' %>
      <%= link_to '查看图片', show_by_place_path(camera_place.id), :class => 'btn' %>
    </td>
    <!--
    <td><%= camera_place.status %></td>
    <td><%= link_to 'Show', camera_place %></td>
    <td><%= link_to 'Edit', edit_camera_place_path(camera_place) %></td>
    <td><%= link_to 'Destroy', camera_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    -->
  </tr>
<% end %>
</table>

app/views/camera_places/new.html.erb
<div class="pull-left">
  <h3>新建监控场所</h3>
</div>
<div class="pull-right">
  <h3>
    <%= link_to '返回', camera_places_path, :class=>"btn" %>
  </h3>
</div>

<%= render 'form' %>

app/views/camera_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @camera_place.place %>
</p>

<p>
  <b>Status:</b>
  <%= @camera_place.status %>
</p>


<%= link_to 'Edit', edit_camera_place_path(@camera_place) %> |
<%= link_to 'Back', camera_places_path %>