config/routes.rb
TheCloudOfImage::Application.routes.draw do

  resources :camera_places
  get "camera_places/add_place_moniter/:camera_place_id" => "camera_places#add_place_moniter", :as => 'add_place_moniter'

  resources :cameras
  get "cameras/show_by_place/:camera_place_id" => "cameras#show_by_place", :as => "show_by_place"

  post "group_api/index"
  post "api_user/index"
  post "api_moniter_place/index"
  post "api_system/index"

  post "api/index"
  get "api/index"
  post "api/upload"
  post "moniter/upload"

  resources :convert_rules

  get "images/display/:filename.:format\!:convert_rule" => "images#convert", :as=>'convert_image'
  get "images/display/:filename" => "images#display", :as=>'display_image'

  resources :images do
  end

  get "site/index"
  get "site/pjax", :as=>'pjax'

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}

  root :to => 'site#index'

end

app/models/camera.rb
class Camera < ActiveRecord::Base
  default_scope order('id DESC')        
  attr_accessible :image_url, :place, :user_id

end

app/controllers/cameras_controller.rb
require "base64"
class CamerasController < ApplicationController
  before_filter :authenticate_user!, :set_page_name

  def show_by_place
    user = current_user
    @place = CameraPlace.find(params[:camera_place_id])

    if not @place or @place.user_id != user.id
      return render_404
    end

    @cameras = @place.cameras.paginate(:page => params[:page], :per_page => 10)

  end

  # GET /cameras
  # GET /cameras.json
  def index
    user = current_user
    @cameras = Camera.where(:user_id => user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cameras }
    end
  end

  # GET /cameras/1
  # GET /cameras/1.json
  def show
    @camera = Camera.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @camera }
    end
  end

  # GET /cameras/new
  # GET /cameras/new.json
  def new
    @camera = Camera.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @camera }
    end
  end

  # GET /cameras/1/edit
  def edit
    @camera = Camera.find(params[:id])
  end

  # POST /cameras
  # POST /cameras.json
  def create
    image_data =  Base64.decode64(params[:image_data])
    image_data = image_data.gsub('data:image/jpeg;base64,', '')
    file_name = Digest::MD5.hexdigest(image_data)
    file_path = "/tmp/#{file_name}.jpeg"
    f=open(file_path, "wb") 
    f.puts(image_data) 
    f.close

    f = open(file_path, "rb")
    uploader = ImageUploader.new
    uploader.store!(f)
    

    @camera = Camera.new
    @camera.image_url = uploader.filename

    user = current_user
    @camera.user_id = user.id
    @camera.camera_place_id = params[:camera_place_id]

    respond_to do |format|
      if @camera.save
        format.html { redirect_to @camera, notice: 'Camera was successfully created.' }
        format.json { render json: @camera, status: :created, location: @camera }
      else
        format.html { render action: "new" }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cameras/1
  # PUT /cameras/1.json
  def update
    @camera = Camera.find(params[:id])

    respond_to do |format|
      if @camera.update_attributes(params[:camera])
        format.html { redirect_to @camera, notice: 'Camera was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cameras/1
  # DELETE /cameras/1.json
  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy

    respond_to do |format|
      format.html { redirect_to cameras_url }
      format.json { head :no_content }
    end
  end

  private
    def set_page_name
      @page_name = "camera_places"
    end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/cameras/_form.html.erb
<%= form_for(@camera) do |f| %>
  <% if @camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camera.errors.count, "error") %> prohibited this camera from being saved:</h2>

      <ul>
      <% @camera.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cameras/edit.html.erb
<h1>Editing camera</h1>

<%= render 'form' %>

<%= link_to 'Show', @camera %> |
<%= link_to 'Back', cameras_path %>

app/views/cameras/index.html.erb
<h3>监控图片</h3>

<table class="table">
  <thead>
    <tr>
      <th>图片</th>
    </tr>
  </thead>

  <tr>
    <td>
      <% @cameras.each do |camera| %>
        <div style='padding:1px; margin:2px; border:1px solid #eee;float:left;'>
          <%= image_tag("/images/display/"+camera.image_url) %>
        </div>
        <!--
        <td><%= link_to 'Show', camera %></td>
        <td><%= link_to 'Edit', edit_camera_path(camera) %></td>
        <td><%= link_to 'Destroy', camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      <% end %>
    </td>
  </tr>
</table>

<br />

<%= link_to 'New Camera', new_camera_path %>

<div class="apple_pagination">
  <%= will_paginate @cameras, :previous_label => '<< 上一页', :next_label => '下一页 >>' %>
</div>

app/views/cameras/new.html.erb
<h1>新增监控</h1>

<!--
<%= render 'form' %>
-->

<video id="video" style="width:320px;height:240px;" autoplay></video>
<br/>
<button id="snap" class="btn sexyButton">Snap Photo</button>
<button id="upload" class="btn">upload</button>
<br/>
<canvas id="canvas" style='display:block' width="320" height="240"></canvas>
<img id="img" src="" />
    <script>
    function hasGetUserMedia() {
        // Note: Opera is unprefixed.
        return !!(navigator.getUserMedia || navigator.webkitGetUserMedia ||
                navigator.mozGetUserMedia || navigator.msGetUserMedia);
    }
    function getMedia()
    {
        return navigator.getUserMedia || navigator.webkitGetUserMedia ||
                navigator.mozGetUserMedia || navigator.msGetUserMedia;
    }

    if (hasGetUserMedia()) {
        // Good to go!
    } else {
        alert('getUserMedia() is not supported in your browser');
    }

    </script>
    <script>
        // Put event listeners into place
        window.addEventListener("DOMContentLoaded", function() {
            // Grab elements, create settings, etc.
            var canvas = document.getElementById("canvas"),
                context = canvas.getContext("2d"),
                video = document.getElementById("video"),
                img = document.getElementById("img"),
                videoObj = { "video": true },
                localMediaStream = null,
                errBack = function(error) {
                    alert("Video capture error: " + error); 
                };

            // Put video listeners into place
            if(navigator.getUserMedia) { // Standard
                navigator.getUserMedia(videoObj, function(stream) {
                    video.src = stream;
                    video.controls = true;

                    localMediaStream = stream;
                }, errBack);
            } else if(navigator.webkitGetUserMedia) { // WebKit-prefixed
                navigator.webkitGetUserMedia(videoObj, function(stream){
                    var vendorURL = window.URL || window.webkitURL;
                    video.src = window.webkitURL.createObjectURL(stream);
                    video.controls = true;
                    localMediaStream = stream;
                }, errBack);
            } else if (navigator.mozGetUserMedia ) {
                alert("moz");
                navigator.mozGetUserMedia(videoObj, function(stream1){
                        alert("==");
                    video.src = window.URL.createObjectURL(stream1);
                    localMediaStream = stream1;
                    video.play();
                }, errBack);
                alert("bbb");
            }

            // Trigger photo take
            document.getElementById("snap").addEventListener("click", function() {
                context.drawImage(video, 0 , 0, 320, 240);
                img.src = canvas.toDataURL('image/webp');
            });

            document.getElementById("upload").addEventListener("click", function() {
                var imgData =canvas.toDataURL("image/webp");
                var data = imgData.substr(23);  
                $.post('<%= cameras_path%>',{ 'image_data' : data }, function(data, textStatus, jqXHR){
                  //success
                }, "json" );
            });

        }, false);
    </script>
<%= link_to 'Back', cameras_path %>

app/views/cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @camera.user_id %>
</p>

<p>
  <b>Image url:</b>
  <%= @camera.image_url %>
</p>

<p>
  <b>Place:</b>
  <%= @camera.place %>
</p>


<%= link_to 'Edit', edit_camera_path(@camera) %> |
<%= link_to 'Back', cameras_path %>

app/views/cameras/show_by_place.html.erb
<div class="pull-left">
  <h3><%= @place.place %> 监控图片</h3>
</div>
<div class="pull-right">
  <h1><%= link_to '返回监控列表', camera_places_path, :class=>'btn btn-primary' %></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>图片</th>
    </tr>
  </thead>

  <tr>
    <td>
      <% @cameras.each do |camera| %>
        <div style='padding:1px; margin:2px; border:1px solid #eee;float:left;'>
          <%= image_tag("/images/display/"+camera.image_url) %>
        </div>
        <!--
        <td><%= link_to 'Show', camera %></td>
        <td><%= link_to 'Edit', edit_camera_path(camera) %></td>
        <td><%= link_to 'Destroy', camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      <% end %>
    </td>
  </tr>
</table>

<br />