config/routes.rb
TheCloudOfImage::Application.routes.draw do

  resources :camera_places
  get "camera_places/add_place_moniter/:camera_place_id" => "camera_places#add_place_moniter", :as => 'add_place_moniter'

  resources :cameras
  get "cameras/show_by_place/:camera_place_id" => "cameras#show_by_place", :as => "show_by_place"

  post "group_api/index"
  post "api_user/index"
  post "api_moniter_place/index"
  post "api_system/index"

  post "api/index"
  get "api/index"
  post "api/upload"
  post "moniter/upload"

  resources :convert_rules

  get "images/display/:filename.:format\!:convert_rule" => "images#convert", :as=>'convert_image'
  get "images/display/:filename" => "images#display", :as=>'display_image'

  resources :images do
  end

  get "site/index"
  get "site/pjax", :as=>'pjax'

  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}

  root :to => 'site#index'

end

app/models/convert_rule.rb
class ConvertRule < ActiveRecord::Base
  attr_accessible :description, :status, :symbol, :title, :user_id
end

app/controllers/convert_rules_controller.rb
class ConvertRulesController < ApplicationController
  before_filter :authenticate_user!, :set_page_name

  # GET /convert_rules
  # GET /convert_rules.json
  def index
    @convert_rules = ConvertRule.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @convert_rules }
    end
  end

  # GET /convert_rules/1
  # GET /convert_rules/1.json
  def show
    @convert_rule = ConvertRule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @convert_rule }
    end
  end

  # GET /convert_rules/new
  # GET /convert_rules/new.json
  def new
    @convert_rule = ConvertRule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @convert_rule }
    end
  end

  # GET /convert_rules/1/edit
  def edit
    @convert_rule = ConvertRule.find(params[:id])
  end

  # POST /convert_rules
  # POST /convert_rules.json
  def create
    @convert_rule = ConvertRule.new(params[:convert_rule])

    @convert_rule.user_id = current_user.id
    @convert_rule.status = "valid"

    respond_to do |format|
      if @convert_rule.save
        format.html { redirect_to @convert_rule, notice: 'Convert rule was successfully created.' }
        format.json { render json: @convert_rule, status: :created, location: @convert_rule }
      else
        format.html { render action: "new" }
        format.json { render json: @convert_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /convert_rules/1
  # PUT /convert_rules/1.json
  def update
    @convert_rule = ConvertRule.find(params[:id])

    respond_to do |format|
      if @convert_rule.update_attributes(params[:convert_rule])
        format.html { redirect_to @convert_rule, notice: 'Convert rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @convert_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convert_rules/1
  # DELETE /convert_rules/1.json
  def destroy
    @convert_rule = ConvertRule.find(params[:id])
    @convert_rule.destroy

    respond_to do |format|
      format.html { redirect_to convert_rules_url }
      format.json { head :no_content }
    end
  end

  private
    def set_page_name
      @page_name = "converts"
    end
end

app/helpers/convert_rules_helper.rb
module ConvertRulesHelper
end

app/views/convert_rules/_form.html.erb
<%= form_for(@convert_rule, :html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @convert_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convert_rule.errors.count, "error") %> prohibited this convert_rule from being saved:</h2>

      <ul>
      <% @convert_rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title  , :class=>"control-label"%>
    <div class="controls">
    <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :symbol  , :class=>"control-label"%>
    <div class="controls">
    <%= f.text_field :symbol %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description  , :class=>"control-label"%>
    <div class="controls">
      <%= f.text_area :description, :rows=>3 %>

    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "创建", :class=>"btn"%>
    </div>
  </div>
<% end %>

app/views/convert_rules/edit.html.erb
<h1>Editing convert_rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @convert_rule %> |
<%= link_to 'Back', convert_rules_path %>

app/views/convert_rules/index.html.erb
<h1>Listing convert_rules</h1>

<table class="table">
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Symbol</th>
    <th>Description</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convert_rules.each do |convert_rule| %>
  <tr>
    <td><%= convert_rule.user_id %></td>
    <td><%= convert_rule.title %></td>
    <td><%= convert_rule.symbol %></td>
    <td><%= convert_rule.description %></td>
    <td><%= convert_rule.status %></td>
    <td><%= link_to 'Show', convert_rule %></td>
    <td><%= link_to 'Edit', edit_convert_rule_path(convert_rule) %></td>
    <td><%= link_to 'Destroy', convert_rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Convert rule', new_convert_rule_path %>

app/views/convert_rules/new.html.erb
<h1>New convert_rule</h1>

<%= render 'form' %>

<%= link_to 'Back', convert_rules_path %>

app/views/convert_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @convert_rule.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @convert_rule.title %>
</p>

<p>
  <b>Symbol:</b>
  <%= @convert_rule.symbol %>
</p>

<p>
  <b>Description:</b>
  <%= @convert_rule.description %>
</p>

<p>
  <b>Status:</b>
  <%= @convert_rule.status %>
</p>

<%= link_to 'Edit', edit_convert_rule_path(@convert_rule) %> |
<%= link_to 'Back', convert_rules_path %>